version: '3.9'
services:
  postgres:
    image: postgres:14@sha256:e7e9c0b3470ebff1b693f3a0a3302eb02505e62d67fc1b42c86c2811b4c6e451
    container_name: postgres_nexi
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=nodo
      - POSTGRES_USER=cfg
      - POSTGRES_PASSWORD=password