version: '3.9'
services:
  postgres:
    image: postgres:14@sha256:ca25035f7e6f74552655a1c5e4a9eb21f85e9d316f1f70371f790ef70095dd58
    container_name: postgres_nexi
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=nodo
      - POSTGRES_USER=cfg
      - POSTGRES_PASSWORD=password