version: '3.9'
services:
  postgres:
    image: postgres:14@sha256:da076311f78c56e4bf6548ef3668fa77fa2865c5efca3f79a6d6bb9b3710b477
    container_name: postgres_nexi
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=nodo
      - POSTGRES_USER=cfg
      - POSTGRES_PASSWORD=password